"""Delete is_published column to post table

Revision ID: 0bd9c1abeebe
Revises: a9429b4e8763
Create Date: 2024-05-26 12:11:48.753500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bd9c1abeebe'
down_revision: Union[str, None] = 'a9429b4e8763'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'is_published')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('is_published', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###
