"""Convert test column to string type in tag table

Revision ID: d7bf81c91f70
Revises: 9a9b43c83792
Create Date: 2024-05-27 06:06:40.059597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'd7bf81c91f70'
down_revision: Union[str, None] = '9a9b43c83792'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tag', 'test', type_=sa.String())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE tag ALTER COLUMN test TYPE DOUBLE PRECISION USING test::DOUBLE PRECISION")
    # ### end Alembic commands ###
